### ISSUE TITLE
The '-R' switch fails due to line 61 (for me at least)

### ISSUE THREAD

**Issue by BodneyC** [tonymorello/trash#1]
Hey, I may be wrong here but on line 61 of trash.sh `confirmall` should be at the end of the line; the `trash -R` command fails if this isn't changed before compilation.

**Comment by tonymorello** [comment]
Yeah this is an old script... I was planning on rewriting the whole thing... When I have time (HA!)
You are welcome to fork it, patch it, send a pull request, etc.
