### ISSUE TITLE
Why not move files to the actual trash bin (~/.Trash)?

### ISSUE THREAD

**Issue by m-ocean-it** [tonymorello/trash#6]
That's a general question. I wonder why you chose the implementation that you chose. Also, where exactly do the files go?

By the way, I've found `trash-cli` utility for Linux that does exactly that: it operates on the actual trash bin.

**Comment by tonymorello** [comment]
Honestly I haven't looked at the ~/.Trash directory. It looks like the way files are trashed can vary between desktop managers so it's probably better to move them to ~/.trash and avoid running into compatibility issues. The idea behind this script was to implement a trash bin for cli-only environments so I never considered cross compatibility with DMs.

The files go into `~/.trash/[file_name]/original/path/to/file.ext` and when restored the whole file path is restored out of the [file_name] folder.

**Comment by possibly-not** [comment]
> The files go into `~/.trash/[file_name]/original/path/to/file.ext` and when restored the whole file path is restored out of the [file_name] folder.

I think this should go into the README :smile:  
I was looking at my DE's wastebin and wondering where my file went. Of course now it makes sense to deal with it in your own way.
